language: scala

scala:
  - 3.3.0    # Adjust based on your Scala version

jdk:
  - openjdk21  # Match this to your project's Java version

script:
  - sbt clean coverage test coverageReport  # Run tests with coverage
  - sbt coverageAggregate                   # Aggregate coverage for multi-module projects

after_success:
  - bash <(curl -s https://codecov.io/bash) -t $TRAVIS_CI_TOKEN  # Upload coverage to Codecov
