name: Scala CI with Codacy Coverage

on:
  push:
    branches: [05-MVC_testing_hand]  # Updated to your branch name
  pull_request:
    branches: [05-MVC_testing_hand]  # Updated to your branch name

jobs:
  build-and-send-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: '21'  # Using Java 21 as requested

      - name: Install SBT
        run: |
          echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
          curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xD24D7D1814E3B4DB" | gpg --dearmor | sudo tee /usr/share/keyrings/sbt-archive-keyring.gpg > /dev/null
          sudo apt-get update
          sudo apt-get install sbt

      - name: Run tests with Scoverage
        run: sbt clean coverage test coverageReport

      - name: Upload coverage to Codacy
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          wget https://github.com/codacy/codacy-coverage-reporter/releases/download/7.2.0/codacy-coverage-reporter-assembly-7.2.0.jar -O codacy-coverage-reporter.jar
          java -jar codacy-coverage-reporter.jar report -l Scala -r target/scala-*/scoverage-report/scoverage.xml
