name: Test workflow

on:
  push:
    branches:

  pull_request:
    branches:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test Scala
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'   # You cajn use 'adopt' or another Java distribution of your choice
          java-version: '21'      # Adjust according to your project’s requirements

      - name: Run tests
        run: sbt coverage test coverageReport

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}  # Uses the secret stored in GitHub Actions

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@cfd0633edbd2411b532b808ba7a8b5e04f76d2c8
