name: Test workflow

on:
  push:
    branches:
  pull_request:
    branches:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test Scala
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for Git data

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Run tests
        run: sbt coverage test coverageReport

      - name: Fix Scoverage Report Paths
        run: sed -i 's|filename="Main.scala"|filename="src/main/scala/Main.scala"|g' target/scala-3.3.3/scoverage-report/scoverage.xml


      - name: Debug Scoverage Report
        run: cat target/scala-3.3.3/scoverage-report/scoverage.xml
      - name: SonarCloud Scoverage Fix
        uses: pervasive-cats/sonarcloud-scoverage-fix@v1.0.1
        with:
          scoverageReport: target/scala-3.2.1/scoverage-report/scoverage.xml
          env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216

        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectBaseDir=/github/workspace
            -Dsonar.projectKey=ShahdLala66_SE_Kitty_Card
            -Dsonar.organization=shahdlala66
            -Dsonar.sources=src/main
            -Dsonar.tests=src/test
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.scala.scoverage.reportPaths=target/scala-3.3.3/scoverage-report/scoverage.xml
            -Dsonar.log.level=DEBUG
            -Dsonar.verbose=true
