name: Test workflow

on:
  push:
    branches:

  pull_request:
    branches:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test Scala
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'   # You cajn use 'adopt' or another Java distribution of your choice
          java-version: '21'      # Adjust according to your project’s requirements

      - name: Run tests
        run: sbt coverage test coverageReport

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}  # Uses the secret stored in GitHub Actions

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@cfd0633edbd2411b532b808ba7a8b5e04f76d2c8

      # Step 6: Analyze with SonarCloud
      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216

        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=ShahdLala66_SE_Kitty_Card
            -Dsonar.organization=shahdlala66
            -Dsonar.scala.scoverage.reportPath=target/scala-*/scoverage-report/scoverage.xml
            -Dsonar.sources=src/main
            -sonar.tests=src/test
            -Dsonar.sourceEncoding=UTF-8

          projectBaseDir: .


